---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  The following CloudFormation Snowflake resource types allow the creation and configuration of
  a Database

Resources:
  NewDatabase:
    Type: Snowflake::Database::Database
    Properties:
      Name: ExampleDatabase
      DataRetentionTimeInDays: 1
      MaxDataExtensionTimeInDays: 1
      DefaultDdlCollation: "en-ci"
      Comment: "This is a comment""
