AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Snowflake::User::User resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/Snowflake-User-User/src/handlers.testEntrypoint
      Runtime: nodejs20.x
      CodeUri: ./

  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/Snowflake-User-User/src/handlers.entrypoint
      Runtime: nodejs20.x
      CodeUri: ./

